"""The document state machine — enforced in one place (see graph.py from Phase 4)."""
from __future__ import annotations

# Happy path
ALINDI = "ALINDI"
OKUNDU = "OKUNDU"
SINIFLANDIRILDI = "SINIFLANDIRILDI"
OZETLENDI = "ÖZETLENDİ"
DOGRULANDI = "DOĞRULANDI"
YONLENDIRILDI = "YÖNLENDİRİLDİ"
TASLAK_HAZIR = "TASLAK_HAZIR"
TESLIM_EDILDI = "TESLİM_EDİLDİ"
YANIT_BEKLIYOR = "YANIT_BEKLİYOR"
YANITLANDI = "YANITLANDI"
TAMAMLANDI = "TAMAMLANDI"

# Branches
TRIYAJ = "TRİYAJ"
INCELEME_GEREKLI = "İNCELEME_GEREKLİ"
REDDEDILDI = "REDDEDİLDİ"

# Ordered happy-path transitions (later phases validate against this).
ORDER = [
    ALINDI, OKUNDU, SINIFLANDIRILDI, OZETLENDI, DOGRULANDI,
    YONLENDIRILDI, TASLAK_HAZIR, TESLIM_EDILDI, YANIT_BEKLIYOR, YANITLANDI, TAMAMLANDI,
]
